name: HouseOfChosenOne
main: com.alphadev.HouseOfChosenOne
author: AlphaDev_
description: Este plugin faz parte de um server de RP e serve como base para o seu funcionamento
version: 1.0
api-version: 1.19
commands:
  houseofchosenone:
    aliases: [chosen, choose, hco]
    description: Use este comando para selecionar uma casa
    permission: hco.use
  citadel:
    aliases: [city, capital]
    description: Use este comando para definir coordenadas para cada uma das capitais de cada casa
    permission: hco.admin
  lobby:
    aliases: [hub]
    description: Use este comando server para retornar a cordenadas da casa escolhida
    permission: hco.lobby
  quest:
    description: Comando usado para abertura de quests atraves dos npcs
    permission: npc.quests
  questTest:
    description: TESTETETSTE
    permission: hco.use
  global:
    aliases: [g]
    description: Define o chat global como padrão
  local:
    aliases: [l]
    description: Define o chat local como padrão
  whisper:
    aliases: [ w, tell ]
    description: Permite o player sussurrar para outro player
  reply:
    aliases: [ r ]
    description: Permite o player sussurrar devolta para o ultimo player que lhe enviou mensagem
  waystone:
    aliases: [ waystone, ws]
    description: Permite ao player Teleportar para outros locais
permissions:
  hco.use:
    default: true
  hco.lobby:
    default: true
  hco.admin:
    default: op
  npc.quests:
    default: op