name: HOCOPlugin
main: com.alphadev.HOCOPlugin
author: AlphaDev_
description: Este plugin faz parte de um server de RP e serve como base para o seu funcionamento
version: 1.0
api-version: 1.19
commands:
  hoco:
    aliases: [ choose, hoco ]
    usage: /command <subcommand> [options]
    description: Use este comando para selecionar uma casa
    permission: hoco.use
  citadel:
    aliases: [ city, capital ]
    description: Use este comando para definir coordenadas para cada uma das capitais de cada casa
    permission: hco.admin
  lobby:
    aliases: [ hub ]
    description: Use este comando server para retornar a cordenadas da casa escolhida
    permission: hco.lobby
  quest:
    description: Comando usado para abertura de quests atraves dos npcs
    permission: npc.quests
  global:
    aliases: [ g ]
    description: Define o chat global como padrão
  local:
    aliases: [ l ]
    description: Define o chat local como padrão
  whisper:
    aliases: [ w, tell ]
    description: Permite o player sussurrar para outro player
  reply:
    aliases: [ r ]
    description: Permite o player sussurrar devolta para o ultimo player que lhe enviou mensagem
permissions:
  hoco.use:
    default: true
  hoco.use.g:
    default: op
  hoco.lobby:
    default: true
  hoco.admin:
    default: op
  npc.quests:
    default: op